# Generated by Django 4.2.6 on 2023-10-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="astronomyshow",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="astronomyshow",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
